# Generated by Django 5.1.7 on 2025-11-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_bot', '0002_channelstosubscribe_delete_telegramadminsid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelstosubscribe',
            options={'verbose_name': "Obuna bo'lish kerak bo'lgan kanallar", 'verbose_name_plural': "Obuna bo'lish kerak bo'lgan kanallar"},
        ),
        migrations.RenameField(
            model_name='channelstosubscribe',
            old_name='chanel_name',
            new_name='name',
        ),
    ]
