# Generated by Django 5.1.7 on 2025-09-15 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('otp_code', models.CharField(max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi OTP',
                'verbose_name_plural': 'Foydalanuvchi OTPlari',
            },
        ),
    ]
