version: '3'

services:
  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx konfiguratsiya faylini konteynerga ko'chirish
      - .:/app  # Django ilovasi va fayllar
    ports:
      - "80:80"  # Nginx porti
    depends_on:
      - django