version: '3'

services:
  django:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ENV
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - django
