# Generated by Django 5.1.7 on 2025-04-08 18:32

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillzToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces_token', models.TextField(unique=True)),
                ('refresh_token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', "O'g'il bolalar uchun"), ('female', 'Qiz bolalar uchun'), ('all', 'Barcha uchun')], default='male', max_length=6, verbose_name='Kimlar uchun:')),
                ('name', models.CharField(default='ok', max_length=100, verbose_name='Kategory nomi (uzb)')),
                ('name_ru', models.CharField(default='ok', max_length=100, verbose_name='Kategory nomi (rus)')),
                ('name_en', models.CharField(default='ok', max_length=100, verbose_name='Kategory nomi (eng)')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xaridor ismi:')),
                ('buyer_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xaridor familiyasi:')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xaridor raqami:')),
                ('address', models.TextField(verbose_name='Xaridor manzili:')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami xarid narxi:')),
                ('payment_method', models.CharField(choices=[('naxt', 'Naxt'), ('karta', 'Karta')], default='naxt', max_length=6, verbose_name='Tolov turi:')),
                ('payment_link', models.URLField(blank=True, null=True, verbose_name='Tolov qilish uchun link:')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Tolanganligi:')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Buyurtma xolati:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Xarid qilingan vaqt:')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ok', max_length=100, verbose_name="O'yinchoq nomi (uzb):")),
                ('name_ru', models.CharField(default='ok', max_length=100, verbose_name="O'yinchoq nomi (rus):")),
                ('name_en', models.CharField(default='ok', max_length=100, verbose_name="O'yinchoq nomi (eng):")),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="O'yinchoq narxi (Faqat so'mda):")),
                ('discount', models.IntegerField(default=0, verbose_name="O'yinchoq chegirmasi: (ixtiyoriy)")),
                ('description', models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida (uzb):")),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida (rus):")),
                ('description_en', models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida (eng):")),
                ('quantity', models.IntegerField(verbose_name="O'yinchoq soni:")),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name="O'yinchoq karobkasidagi kod:")),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='You tubdan video joylash:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategoriya:')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Buyurtma soni:')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami summa:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shop.products', verbose_name="O'yinchoq nomi:")),
            ],
            options={
                'verbose_name': "Buyurtmadagi o'yinchoq",
                'verbose_name_plural': "Buyurtmadagi o'yinchoqlar",
            },
        ),
        migrations.CreateModel(
            name='LikedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.products')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='CommentProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.products')),
            ],
        ),
    ]
