# Generated by Django 5.1.7 on 2025-09-19 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_created_datetime_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('oq', 'Oq'), ('qora', 'Qora'), ('kulrang', 'Kulrang'), ('qizil', 'Qizil'), ('yashil', 'Yashil'), ('ko‘k', 'Ko‘k'), ('sariq', 'Sariq'), ('to‘q sariq', 'To‘q sariq'), ('pushti', 'Pushti'), ('binafsha', 'Binafsha'), ('jigarrang', 'Jigarrang'), ('bej', 'Bej'), ('oltin', 'Oltin'), ('kumush', 'Kumush')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(choices=[('oq', 'Oq'), ('qora', 'Qora'), ('kulrang', 'Kulrang'), ('qizil', 'Qizil'), ('yashil', 'Yashil'), ('ko‘k', 'Ko‘k'), ('sariq', 'Sariq'), ('to‘q sariq', 'To‘q sariq'), ('pushti', 'Pushti'), ('binafsha', 'Binafsha'), ('jigarrang', 'Jigarrang'), ('bej', 'Bej'), ('oltin', 'Oltin'), ('kumush', 'Kumush')], default='oq', max_length=20, verbose_name="O'yinchoq rangi:"),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, to='shop.colors', verbose_name="O'yinchoq rangi:"),
        ),
    ]
