# Generated by Django 5.1.7 on 2025-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
