# Generated by Django 5.1.7 on 2025-04-02 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoriya', 'verbose_name_plural': 'Categoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='imageproducts',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': "Buyurtmadagi o'yinchoq", 'verbose_name_plural': "Buyurtmadagi o'yinchoqlar"},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imageproducts',
            name='image',
            field=models.ImageField(upload_to='toy_images/', verbose_name="O'yinchoq uchun rasm (istagancha)"),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Xaridor manzili:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xaridor ismi:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xaridor raqami:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xaridor familiyasi:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Xarid qilingan vaqt:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Tolanganligi:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Tolov qilish uchun link:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('naxt', 'Naxt'), ('karta', 'Karta')], default='naxt', max_length=6, verbose_name='Tolov turi:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Buyurtma xolati:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami xarid narxi:'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Buyurtma soni:'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami summa:'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Categoriya:'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida:"),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=0, verbose_name="O'yinchoq chegirmasi: (ixtiyoriy)"),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name="O'yinchoq nomi:"),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name="O'yinchoq narxi:"),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(verbose_name="O'yinchoq soni:"),
        ),
        migrations.AlterField(
            model_name='products',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='You tubdan video joylash:'),
        ),
    ]
