# Generated by Django 5.1.7 on 2025-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_colors_name_alter_orderitem_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('red', 'Qizil'), ('green', 'Yashil'), ('blue', 'Ko‘k'), ('yellow', 'Sariq'), ('orange', 'To‘q sariq'), ('pink', 'Pushti'), ('violet', 'Binafsha'), ('brown', 'Jigarrang'), ('gold', 'Oltin'), ('silver', 'Kumush')], max_length=50, unique=True),
        ),
    ]
