# Generated by Django 5.1.7 on 2025-04-05 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_imageproducts_image_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_gender', models.CharField(choices=[('male', 'Ogil bollar'), ('female', 'Qiz bollar')], default='male', max_length=6, verbose_name='Kim uchun:')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='price_all',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Buyurtma xolati:'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shop.products', verbose_name="O'yinchoq nomi:"),
        ),

    ]
