# Generated by Django 5.1.7 on 2025-09-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_colors_options_alter_colors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='imageproducts',
            name='color',
            field=models.CharField(choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('red', 'Qizil'), ('green', 'Yashil'), ('blue', 'Ko‘k'), ('yellow', 'Sariq'), ('orange', 'To‘q sariq'), ('pink', 'Pushti'), ('violet', 'Binafsha'), ('brown', 'Jigarrang'), ('gold', 'Oltin'), ('silver', 'Kumush')], default='white', max_length=20, verbose_name="O'yinchoq rangi:"),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.imageproducts', verbose_name="O'yinchoq rangi:"),
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
