# Generated by Django 5.1.7 on 2025-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_options_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('male', "O'g'il bolalar uchun"), ('female', 'Qiz bolalar uchun')], default='male', max_length=6, verbose_name='Kimlar uchun:'),
        ),
    ]
