# Generated by Django 5.1.7 on 2025-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_products_color_remove_orderitem_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('red', 'Qizil'), ('green', 'Yashil'), ('blue', 'Ko‘k'), ('yellow', 'Sariq'), ('orange', 'To‘q sariq'), ('pink', 'Pushti'), ('violet', 'Binafsha'), ('brown', 'Jigarrang'), ('gold', 'Oltin'), ('silver', 'Kumush')], default='white', max_length=20, verbose_name="O'yinchoq rangi:"),
        ),
    ]
