# Generated by Django 5.1.7 on 2025-04-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_gendercategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenderCategory',
        ),
    ]
