# Generated by Django 5.1.7 on 2025-04-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('male', "O'g'il bolalar uchun"), ('female', 'Qiz bolalar uchun'), ('all', 'Barcha uchun')], default='male', max_length=6, verbose_name='Kimlar uchun:'),
        ),
    ]
