# Generated by Django 5.1.7 on 2025-09-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_orderitem_image_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField( max_length=20, unique=True, verbose_name='Buyurtma raqami:'),
            preserve_default=False,
        ),
    ]
