# Generated by Django 5.1.7 on 2025-04-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='ok', max_length=100, verbose_name='Kategory nomi (eng)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='ok', max_length=100, verbose_name='Kategory nomi (rus)'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida (eng):"),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida (rus):"),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(default='ok', max_length=100, verbose_name="O'yinchoq nomi (eng):"),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(default='ok', max_length=100, verbose_name="O'yinchoq nomi (rus):"),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategoriya:'),
        ),
    ]
