# Generated by Django 5.1.7 on 2025-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sotuvchi kodi:'),
        ),
    ]
