# Generated by Django 5.1.7 on 2025-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_name_en_remove_category_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '📄 Oyinchoq exel yuklash',
                'managed': False,
            },
        ),
    ]
