# Generated by Django 5.1.7 on 2025-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_name_remove_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='ok', max_length=100, verbose_name='Kategory nomi (uzb)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="O'yinchoq xaqida (uzb):"),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_uz',
            field=models.CharField(default='ok', max_length=100, verbose_name="O'yinchoq nomi (uzb):"),
        ),
    ]
