# Generated by Django 5.1.7 on 2025-04-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_name_uz_alter_products_description_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description_uz',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name_uz',
            new_name='name',
        ),
    ]
