# Generated by Django 5.1.7 on 2025-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_name_uz_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name="O'yinchoq narxi (Faqat so'mda):"),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
