# Generated by Django 5.1.7 on 2025-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproducts',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name="Rangdagi o'yinchoq soni:"),
        ),
    ]
