# Generated by Django 5.1.7 on 2025-04-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer_number',
            new_name='phone_number',
        ),

    ]
