# Generated by Django 5.1.7 on 2025-10-06 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_imageproducts_quantity'),
        ('users', '0004_customuser_lang_customuser_lat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('red', 'Qizil'), ('green', 'Yashil'), ('blue', 'Ko‘k'), ('yellow', 'Sariq'), ('orange', 'To‘q sariq'), ('pink', 'Pushti'), ('violet', 'Binafsha'), ('brown', 'Jigarrang'), ('gold', 'Oltin'), ('silver', 'Kumush')], default='white', max_length=20, verbose_name="O'yinchoq rangi:")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Savatcha',
                'verbose_name_plural': 'Savatchalar',
            },
        ),
    ]
