# Generated by Django 5.1.7 on 2025-10-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
