# Generated by Django 5.1.7 on 2025-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_buyer_number_order_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillzToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces_token', models.TextField(unique=True)),
                ('refresh_token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name="O'yinchoq karobkasidagi kod:"),
        ),

    ]
