# Generated by Django 5.1.7 on 2025-10-10 15:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_products_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummymodel',
            options={'managed': False, 'verbose_name_plural': '📄 O‘yinchoqlarni Excel orqali yuklash'},
        ),
        migrations.RemoveField(
            model_name='imageproducts',
            name='color',
        ),
        migrations.RemoveField(
            model_name='imageproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='imageproducts',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(choices=[('white', 'Oq'), ('black', 'Qora'), ('gray', 'Kulrang'), ('red', 'Qizil'), ('green', 'Yashil'), ('blue', 'Ko‘k'), ('yellow', 'Sariq'), ('orange', 'To‘q sariq'), ('pink', 'Pushti'), ('violet', 'Binafsha'), ('brown', 'Jigarrang'), ('gold', 'Oltin'), ('silver', 'Kumush')], max_length=20, verbose_name="O'yinchoq rangi:")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='O‘sha rangdagi soni:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.products')),
            ],
            options={
                'verbose_name': 'Mahsulot rangi',
                'verbose_name_plural': 'Mahsulot ranglari',
            },
        ),
        migrations.AddField(
            model_name='imageproducts',
            name='color_variant',
            field=models.ForeignKey(null=True,
        blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productcolor'),
            preserve_default=False,
        ),
    ]
