# Generated by Django 5.1.7 on 2025-10-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_dummymodel_options_remove_imageproducts_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproducts',
            name='color_variant',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='color_variants', to='shop.imageproducts'),
        ),
    ]
