# Generated by Django 5.1.7 on 2025-10-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_imageproducts_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproducts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rasm nomi (ixtiyoriy):'),
        ),
    ]
