# Generated by Django 5.1.7 on 2025-10-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_imageproducts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Savatchaga qo'shilgan vaqtdagi o'yinchoq narxi (so'mda):"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Buyurtma vaqtidagi o'yinchoq narxi (so'mda):"),
            preserve_default=False,
        ),
    ]
