# Generated by Django 5.1.7 on 2025-12-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cart_price_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manufacturer_code',
        ),
    ]
