# Generated by Django 5.1.7 on 2025-12-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_products_manufacturer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='imageproducts',
            name='product',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.products', verbose_name="O'yinchoq:"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name="O'yinchoq soni omborda:"),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
