# Generated by Django 5.1.7 on 2025-12-04 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_cart_color_remove_orderitem_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillzToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.TextField(verbose_name='Billz tokeni:')),
            ],
            options={
                'verbose_name': 'Billz Token',
                'verbose_name_plural': 'Billz Tokenlar',
            },
        ),
    ]
