# Generated by Django 5.1.7 on 2025-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_billztoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billztoken',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='billztoken',
            name='expires_in',
            field=models.IntegerField(default=0, verbose_name='Token amal qilish muddati (soniya):'),
        ),
    ]
