# Generated by Django 5.1.7 on 2025-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='billz_position',
            field=models.CharField(blank=True, default='main_1', max_length=100, null=True, verbose_name='Billz pozitsiyasi (ixtiyoriy):'),
        ),
    ]
