# Generated by Django 5.1.7 on 2025-12-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_products_billz_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="O'yinchoq ko'rilganligi:"),
        ),
    ]
